import { Student } from "./types";

export const seedStudents: Student[] = [
  { id: "1", name: "Ailton Laureiro Lopez Chinombiano", class: "1", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "2", name: "Asher Ngazamune Sitoe", class: "1", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "3", name: "Ayana Liz De Mário Nhatumbo", class: "1", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "4", name: "Ayla Beatriz Mutemba", class: "1", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "5", name: "Ayrton Rogerio Elvino Langa", class: "1", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "6", name: "Celma Flora Benjamim", class: "1", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "7", name: "Derek Tavares Zunguza", class: "1", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "8", name: "Elias Helio Pelembe", class: "1", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "9", name: "Elonio Paulo Matsinhe", class: "1", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "10", name: "Fernandes Da Nilza Emídio Chigenge", class: "1", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "11", name: "Hayton Adonai Sitoé", class: "1", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "12", name: "Ian Eduardo Zucula", class: "1", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "13", name: "Jeovana Da Abhigail Mavie", class: "1", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "14", name: "Jhaden Oscar De Melo", class: "1", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "15", name: "Kayala Timana", class: "1", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "16", name: "Kayane Stelio Nhanengue", class: "1", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "17", name: "Lemuel Rocha Matavele", class: "1", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "18", name: "Leopoldino Custodio Changula Junior", class: "1", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "19", name: "Maida Anselmo Marrumete", class: "1", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "20", name: "Mikhail Colce Verlopp", class: "1", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "21", name: "Momed Fahardino Ussene", class: "1", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "22", name: "Nelly Jefson Matimbe", class: "1", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "23", name: "Niyara Luanda Chivura", class: "1", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "24", name: "Shaden Óscar De Melo", class: "1", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "25", name: "Shelton Armando Tazine", class: "1", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "26", name: "Sidney Leopoldino Changule", class: "1", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "27", name: "Uchenna Daniel Savanguane", class: "1", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "28", name: "Wilton Abicio Bango", class: "1", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "29", name: "Allana Stelio Uane", class: "2", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "30", name: "Amândio Enoque Júnior", class: "2", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "31", name: "Camila Ali Cutane", class: "2", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "32", name: "Cristiane Macueve", class: "2", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "33", name: "Elyn Lameque", class: "2", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "34", name: "Emanuela Elisa Bie", class: "2", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "35", name: "Emílio Amândio Inoque", class: "2", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "36", name: "Jhonathan José", class: "2", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "37", name: "Keyla Braga MUlima", class: "2", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "38", name: "Kyara Balbina Sumbi", class: "2", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "39", name: "Lesley Pinga", class: "2", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "40", name: "Nataniel Delso", class: "2", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "41", name: "Orlando Lucas", class: "2", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "42", name: "Samy Eckson Manjate", class: "2", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "43", name: "Sherlon Bulande", class: "2", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "44", name: "Tanaya Fumo", class: "2", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "45", name: "Wendy Salomao", class: "2", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "46", name: "Whitney Kiesha Macuácua", class: "2", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "47", name: "Yandra Costa Aguiar", class: "2", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "48", name: "Alícia Sérgio Sitoé", class: "3", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "49", name: "Alzineide Sérgio Sitoé", class: "3", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "50", name: "Anastâncio Da Izaura Carlitos", class: "3", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "51", name: "Caio António Bachir", class: "3", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "52", name: "Chloe Nyiquiwe Samo Gudo", class: "3", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "53", name: "Creyson Crimildo", class: "3", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "54", name: "Edleusia Francisco", class: "3", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "55", name: "Haniel Sulemane", class: "3", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "56", name: "Helvia Mario", class: "3", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "57", name: "Juaila Elina Cossa", class: "3", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "58", name: "Kaick Mendes", class: "3", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "59", name: "Kaylon Ngomana", class: "3", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "60", name: "Larsen Jancinto", class: "3", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "61", name: "Lucineide Machava", class: "3", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "62", name: "Marlon Langa", class: "3", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "63", name: "Nazle Arlindo", class: "3", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "64", name: "Ricardo Agnaldo Lemela", class: "3", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "65", name: "Shamira De Fátima", class: "3", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "66", name: "Shanyla Felix Tembe", class: "3", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "67", name: "Sheila Marcela", class: "3", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "68", name: "Valdemiro Flugêncio", class: "3", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "69", name: "Wilton Armando Tuzine", class: "3", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "70", name: "Yasmin Luis Muiambo", class: "3", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "71", name: "Shenice Muchanga", class: "3", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "72", name: "Wesley Cuamba", class: "3", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "73", name: "Adnercia Aylton Chilaule", class: "4", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "74", name: "Adriel Domingos", class: "4", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "75", name: "Alicia Patricia", class: "4", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "76", name: "Alisha Monteiro", class: "4", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "77", name: "Allen Armando Mabongo", class: "4", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "78", name: "Assucena Ilídio", class: "4", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "79", name: "Dallen Marcelino Hou", class: "4", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "80", name: "Delso Cleyde", class: "4", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "81", name: "Diego lopez Chinombiano", class: "4", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "82", name: "Dumane Jorge Tamele", class: "4", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "83", name: "Enzo Carlos", class: "4", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "84", name: "Gabriela Britney Cupane", class: "4", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "85", name: "Gerson Alberto Sumbi", class: "4", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "86", name: "Heliana Samuel Justino", class: "4", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "87", name: "Kael Amalia Rungo", class: "4", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "88", name: "Kayon Joaquim Norte", class: "4", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "89", name: "Kayson Miquitar Pedro", class: "4", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "90", name: "Kiane Amelia Rung", class: "4", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "91", name: "Kiyandra Orlando Sangue", class: "4", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "92", name: "Lakisha Da Alda", class: "4", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "93", name: "Luana Cacilda Muianga", class: "4", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "94", name: "Maron Virgílio Munharo Colaço", class: "4", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "95", name: "Michela Nazir Chirumno", class: "4", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "96", name: "Mmawra Da Yivan Fernandes", class: "4", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "97", name: "Moreira Camacho", class: "4", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "98", name: "Neelan Luanda Chivura", class: "4", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "99", name: "Nkhenson Teodomiro Buque", class: "4", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "100", name: "Romel Gabriel Munharo Colaço", class: "4", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "101", name: "Salvador Banze", class: "4", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "102", name: "Silvio Arsenio", class: "4", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "103", name: "Tales Eduardo Macovole", class: "4", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "104", name: "Treyson Arsénio Munguambe", class: "4", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "105", name: "Wanica Cumbi", class: "4", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "106", name: "Wesney Eldo Maibasse", class: "4", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "107", name: "Yasmin Marilia Dombole", class: "4", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "108", name: "Yunique Helder Sabão", class: "4", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "109", name: "Alberto Zlatan", class: "5", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "110", name: "Aldir Alfredo Muapuhane", class: "5", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "111", name: "Ana  Alexia Meireles Verlopp", class: "5", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "112", name: "Breno Benjamim Moia", class: "5", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "113", name: "Calton Boaventura", class: "5", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "114", name: "Celsia Arão Matola", class: "5", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "115", name: "Daiane Daniel Cunica", class: "5", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "116", name: "Delvin Davi Chiponde", class: "5", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "117", name: "Dercio Miguel", class: "5", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "118", name: "Djassy Félix Nhatumbo", class: "5", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "119", name: "Elvis Fausto", class: "5", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "120", name: "Érick Sérgio Dzivane", class: "5", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "121", name: "Felda Alfredo Chitsulete", class: "5", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "122", name: "Helfio Januario Vilanculos", class: "5", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "123", name: "Jonathan Macaringue", class: "5", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "124", name: "Kayane Venancio", class: "5", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "125", name: "Kayra Wanga", class: "5", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "126", name: "Kedson Carlos Chilundo", class: "5", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "127", name: "Luther Ian Timana", class: "5", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "128", name: "Mario Alexandre Bango", class: "5", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "129", name: "Ôshley Samy Bilize", class: "5", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "130", name: "Ruth Noemi Matusse", class: "5", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "131", name: "Shayron Ricardo", class: "5", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "132", name: "Tácio Basílio Massochua", class: "5", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "133", name: "Taylon Nkateco Mahumana", class: "5", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "134", name: "Wanica Armindo Cumbe", class: "5", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "135", name: "Wanila Wiliamo Rubi", class: "5", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "136", name: "Winny Quenasse Ngomane", class: "5", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "137", name: "Yulsia Francisco Chico", class: "5", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "138", name: "Yuston Matlavane", class: "5", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "139", name: "Edwin Muchanga", class: "5", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "140", name: "Bruna Matimbe", class: "5", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "141", name: "Benilton Antonio", class: "5", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "142", name: "Kayron Langa", class: "5", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "143", name: "Adelelina Mário Serafim", class: "6", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "144", name: "Aleck Caitro", class: "6", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "145", name: "Alexandra Vanessa", class: "6", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "146", name: "Alzira Joaquim Malunga", class: "6", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "147", name: "Ayumerson", class: "6", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "148", name: "Carlisha Marieta", class: "6", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "149", name: "Carolina Felisberto Chicala", class: "6", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "150", name: "Daniela Sarifa Matabele", class: "6", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "151", name: "Deywid Wezu Claudio Ngulele", class: "6", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "152", name: "Edna Francisco", class: "6", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "153", name: "Edness Rindzela Samo Gudo", class: "6", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "154", name: "Elen Luis Muchanga", class: "6", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "155", name: "Gabriel Rui", class: "6", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "156", name: "Guift Chai-Chai", class: "6", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "157", name: "Hilleil Sulemane", class: "6", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "158", name: "Isabel António Muchanga", class: "6", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "159", name: "Janice Uamuce", class: "6", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "160", name: "Kaylane Claúdio Mussa Abubacar", class: "6", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "161", name: "Kayron Hilario Tembe", class: "6", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "162", name: "Kiyana Francisco Zualo", class: "6", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "163", name: "Lirandzo Da Margarida Sibinde", class: "6", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "164", name: "Luana Jorge Tamele", class: "6", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "165", name: "Lúcia Henriques", class: "6", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "166", name: "Lúmina Lázaro", class: "6", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "167", name: "Margarida Mariamo Pacheco Xavier", class: "6", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "168", name: "Mizan Luanda Chivura", class: "6", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "169", name: "Shirley Elisa Bilale", class: "6", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "170", name: "Victoria Luegi Tsinini", class: "6", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "171", name: "Vistar Thokhose", class: "6", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "172", name: "Wesley Thopi Dimande", class: "6", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "173", name: "Yalens Nora Macamo", class: "6", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "174", name: "Yanni Varela", class: "6", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "175", name: "Alinny Shelton Langa", class: "7", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "176", name: "Anésia Wilma Macamo", class: "7", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "177", name: "Cleiton Angelo Manhica", class: "7", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "178", name: "Eliel Helio", class: "7", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "179", name: "Garfield Mucavel", class: "7", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "180", name: "Hassan Absalao Bachir", class: "7", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "181", name: "Jasmin Elaine Mutisse", class: "7", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "182", name: "Jenny Eldo Maibasse", class: "7", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "183", name: "Jose Alberto Santana", class: "7", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "184", name: "Kasey Arsénio Munguambe", class: "7", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "185", name: "Kendal Merelin", class: "7", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "186", name: "Lisangela Cacilda Macave", class: "7", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "187", name: "Maksood Fralahy Capaia", class: "7", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "188", name: "Matsunaga Renato Chaguala", class: "7", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "189", name: "Neil Lameque Matimbe", class: "7", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "190", name: "Paulo Aires", class: "7", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "191", name: "Raquel Daniel Magib", class: "7", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "192", name: "Shannaya Da Silva Come", class: "7", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "193", name: "Shanyla Tavares Zunguze", class: "7", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "194", name: "Shelsia Da Suzy Chemane", class: "7", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "195", name: "Sunayla Hibrahimo", class: "7", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "196", name: "Tania Antonio", class: "7", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "197", name: "Teofilo Do Melo", class: "7", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "198", name: "Thulane Valter Guiliche", class: "7", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "199", name: "Wanga Chanel Ngoca", class: "7", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "200", name: "Wendy Gil Howana", class: "7", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "201", name: "Weyna Deyse", class: "7", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "202", name: "Wezu Derick Manjate", class: "7", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "203", name: "Wezu Jorge Matsinhe", class: "7", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "204", name: "Whitney Cuamba", class: "7", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "205", name: "Widney Valdemiro Nhanala", class: "7", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "206", name: "Yani Luis Muianga", class: "7", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "207", name: "Aldevina Isaias", class: "8", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "208", name: "Aike Luis Macheve", class: "8", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "209", name: "Andrea Andre", class: "8", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "210", name: "Andricia Osvaldo Cunica", class: "8", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "211", name: "Ayusca", class: "8", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "212", name: "Elvis tomas culo", class: "8", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "213", name: "Hadriel Matabel", class: "8", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "214", name: "Khelven Luis Muchanga", class: "8", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "215", name: "Kyara Amândio", class: "8", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "216", name: "Marinela Isac", class: "8", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "217", name: "Melvina Osvaldo Cunica", class: "8", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "218", name: "Muaziza Orlando Selemane", class: "8", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "219", name: "Sara Bernadete", class: "8", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "220", name: "Sasia Salomao Nhacala", class: "8", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "221", name: "Tiffany Ayane Estafeira", class: "8", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "222", name: "Victoria Francisca Massinga", class: "8", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "223", name: "Wilson Nazir Chirumbo", class: "8", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "224", name: "Yani Francisca Mutemba", class: "8", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "225", name: "Albertina Matola", class: "9", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "226", name: "Aurea Alfredo Muhapuane", class: "9", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "227", name: "Ayusca", class: "9", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "228", name: "Bibina Hassan Faruck", class: "9", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "229", name: "Erickson Mateus Parafina", class: "9", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "230", name: "Eugénio Guirrugo", class: "9", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "231", name: "Geralda Geraldo", class: "9", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "232", name: "Isla Gérvasio Micas", class: "9", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "233", name: "Keywane Jorge Chai-Chai", class: "9", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "234", name: "Lameque Matimbe", class: "9", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "235", name: "Marven Maphepa Magagule", class: "9", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "236", name: "Nordino Gabriel Zango", class: "9", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "237", name: "Yurgan Wiliamo Rubi", class: "9", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "238", name: "Adamita Armando Mabongo", class: "10", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "239", name: "Cacilda Luis Muchanga", class: "10", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "240", name: "Denise José Uissitone", class: "10", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "241", name: "Dércio Bilale", class: "10", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "242", name: "Hassan Absalao Bachir", class: "10", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "243", name: "Helga Ivone Evaristo Matavele", class: "10", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "244", name: "Kherolaxminy Joaquim Norte", class: "10", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "245", name: "Luana Clara Tembe", class: "10", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "246", name: "Marcin Antonio", class: "10", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "247", name: "Mirion Arão Malate", class: "10", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "248", name: "Sacha Joana Nhalivilo", class: "10", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "249", name: "Samuel Justino", class: "10", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "250", name: "Sheyser Bulande", class: "10", room: "A", gender: "M", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "251", name: "Tayla Karina Clarêncio", class: "10", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "252", name: "Teresa Marcos Matola", class: "10", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "253", name: "Wendy Michelle  Fernandes", class: "10", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "254", name: "Yasmin Mússa Abubacar", class: "10", room: "A", gender: "F", situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "255", name: "Alícia Augusto Manhiça", class: "11", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "256", name: "Clayton Chauze Nhatumbuo", class: "11", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "257", name: "Epifania Felicidade Guiboane", class: "11", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "258", name: "Gerson Tomas Culo", class: "11", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "259", name: "Matias Salomao", class: "11", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "260", name: "Nayra élcio Menete", class: "11", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "261", name: "Vagner Da Graça Guirrugo", class: "11", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "262", name: "Lina cossa", class: "12", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "263", name: "Mayra dos santos Sitoe", class: "12", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "264", name: "Shanaya Nhatumbo", class: "12", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "265", name: "Shenyla Mienda", class: "12", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "266", name: "Walter José Uissitone", class: "12", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
  { id: "267", name: "Yanick Davide", class: "12", room: "A", gender: undefined, situation: "Novo Ingresso", parentPhones: [], paymentStatus: {} },
];
